"""Add user_id to ParkingSession and update relationships

Revision ID: 26c4790c2121
Revises: b1a1606e4ee1
Create Date: 2024-06-15 18:16:43.180050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c4790c2121'
down_revision: Union[str, None] = 'b1a1606e4ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
